Repository anchalchaturvedi08/Signature-App, pull requests merged in 2025-01, with the labels that each got.

#34 Home page with new design added.
  canva.css
  canva.html
  canva.js
  index.html
  style.css
Labels: enhancement, SWOC'25, intermediate

#35 login and signup page with new design added
  login.css
  login.html
  logo.svg
  signup.html
Labels: enhancement, SWOC'25, intermediate

#37 folder structure updated and tested properly
  assets/css/canva.css
  assets/css/login.css
  assets/css/type.css
  assets/favicon/favicon.png
  index.html
  pages/canva.html
  pages/login.html
  pages/signup.html
  pages/type.html
  script.js
  scripts/canva.js
  scripts/type.js
  style.css
Labels: SWOC'25, beginner

#41 added a Back button
  assets/css/canva.css
  assets/css/type.css
  assets/images/back.png
  pages/canva.html
  pages/type.html
Labels: enhancement, SWOC'25, beginner

#40 Add Eraser Button and Brush size change
  assets/css/canva.css
  index.html
  pages/canva.html
  scripts/canva.js
  style.css
Labels: enhancement, SWOC'25, beginner
